server: # REST server
  port: 5555
  address: 157.245.4.70
spring:
  main:
    banner-mode: log
lavalink:
  server:
    password: discoardbot165
    ws:
      port: 5555
      host: 157.245.4.70
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      mixer: true
      http: true
      local: false
    bufferDurationMs: 1000
    youtubePlaylistLoadLimit: 600
    gc-warnings: true

metrics:
  prometheus:
    enabled: false
    endpoint: /metrics

sentry:
  dsn: ""
#  tags:
#    some_key: some_value
#    another_key: another_value

logging:
  file:
    max-history: 30
    max-size: 1GB
  path: ./logs/

  level:
    root: INFO
    lavalink: INFO
